version: 2.1
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-ms-teams
            source /usr/local/share/virtualenvs/tap-ms-teams/bin/activate
            uv pip install -U setuptools
            uv pip install .[dev]
      - add_ssh_keys
      - run:
          name: "JSON Validator"
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_ms_teams/schemas/*.json
      - run:
          name: 'Pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-ms-teams/bin/activate
            uv pip install pylint
            pylint tap_ms_teams -d C,R,W
      # - run:
      #     name: "Unit Tests"
      #     command: |
      #       source /usr/local/share/virtualenvs/tap-ms-teams/bin/activate
      #       uv pip install pytest coverage parameterized
      #       coverage run -m pytest tests/unittests
      #       coverage html
      #     when: always
      # - store_test_results:
      #     path: test_output/report.xml
      # - store_artifacts:
      #     path: htmlcov
      # - run:
      #     name: 'Integration Tests'
      #     command: |
      #       aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
      #       source dev_env.sh
      #       source /usr/local/share/virtualenvs/tap-tester/bin/activate
      #       run-test --tap=tap-ms-teams \
      #                  --target=target-stitch \
      #                  --orchestrator=stitch-orchestrator \
      #                  --email=harrison+sandboxtest@stitchdata.com \
      #                  --password=$SANDBOX_PASSWORD \
      #                  --client-id=50 \
      #                  tests
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
